### PR TITLE
Support ruby 3.0.0

### LINKED ISSUE #203: "undefined method `to_sym' for {:on=>:looking_for}:Hash\nDid you mean? to_s\n to_set"
I just upgraded the project to Ruby 3.0.0 from 2.7.2 and it giving an error on `scoped_search on: :looking_for` in model file 
Any have any solution to this

### PR DESCRIPTION
**Pull request by anderscarling**
This addresses the only issue I could find running tests under ruby 3.0.0.

A few tests fails when running under `Gemfile` but that seems to be due to an error with rails 6.1 and habtm joins. The same tests fails under ruby 2.7.2

Using `Gemfile.activerecord60_with_activesupport60` all tests runs under ruby 3.0.0 after this fix.

Closes #203

### CODE REVIEW

File: lib/scoped_search/definition.rb [hunk 1]
```diff
@@ -306,7 +306,8 @@ def default_fields
 
     # Defines a new search field for this search definition.
     def define(*args)
-      Field.new(self, *args)
+      options = args.last.is_a?(Hash) ? args.pop : {}
+      Field.new(self, *args, **options)
     end
```
Comment (adamruzicka) [inline lib/scoped_search/definition.rb:311]: Wouldn't something like this be cleaner? Not sure if it works on old (2.0ish) ruby though

```ruby
def define(*args, **kwargs)
  Field.new(self, *args, **kwargs)
end
```

Comment (anderscarling) [reply lib/scoped_search/definition.rb:311]: Tbh I can’t remember if there is a good reason not to do it like that. 

If it works on all needed

**Comment by adamruzicka** [comment]
Thank you @anderscarling !

File: lib/scoped_search/definition.rb (hunk 1 above)
Comment (stasl) [reply lib/scoped_search/definition.rb]: @adamruzicka doesn't work with ruby 3.0.2
