### ISSUE TITLE
scoped_search not working with Ruby 3.0.2

### ISSUE THREAD

**Issue by richardkmiller** [wvanbergen/scoped_search#209]
For me, the patch in #204 isn't sufficient to make scoped_search work with Ruby 3.0.2. ([Also mentioned by @stasl](https://github.com/wvanbergen/scoped_search/pull/204#discussion_r698502712).)

Gemfile: `gem 'scoped_search', github: 'wvanbergen/scoped_search', branch: 'master'`

Model: `scoped_search on: :url`

Error on page load: `undefined method 'to_sym' for {:on=>:url}:Hash`

First 3 lines of stack trace:
```
scoped_search (92939afa16dd) lib/scoped_search/definition.rb:53:in 'initialize'
scoped_search (92939afa16dd) lib/scoped_search/definition.rb:309:in 'new'
scoped_search (92939afa16dd) lib/scoped_search/definition.rb:309:in 'define'
```

Versions: 
* scoped_search master/92939afa16dd
* Ruby 3.0.2
* Rails 6.1.4.1
* ActiveRecord 6.1.4.1

FYI, @anderscarling's monkey patch in #203 DOES work.

Let me know if you need any other info! Thank you!

**Comment by anderscarling** [comment]
Yeah, it seems to fix all issues when running the test suite.

**Comment by anderscarling** [comment]
@richardkmiller Should be fixed as #210 is merged now. :)

**Comment by richardkmiller** [comment]
@anderscarling Great news! I tested it here and it worked great. I was able to remove the monkey patch. Thank you!
